name: Build and Lint Blazor App

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the Blazor project
        run: dotnet build --configuration Release

      - name: Run linting for C#
        run: dotnet format --verify-no-changes

      - name: Show fun messages on failure
        if: failure()
        run: echo "Something went wrong! But don't worry, you'll fix it soon 🚀."

      - name: Celebrate success with a joke
        if: success()
        run: |
          curl -s https://official-joke-api.appspot.com/random_joke | jq -r '.setup + " - " + .punchline'
